# Generated by Django 4.1.3 on 2022-11-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcard",
            name="deck",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.deck",
            ),
        ),
    ]
