# Generated by Django 4.1.3 on 2022-11-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_benefitclub_course_grade_module_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="lastname",),
        migrations.RemoveField(model_name="student", name="name",),
        migrations.RemoveField(model_name="student", name="nickname",),
        migrations.RemoveField(model_name="student", name="proflie_picture",),
        migrations.RemoveField(model_name="teacher", name="lastname",),
        migrations.RemoveField(model_name="teacher", name="name",),
        migrations.RemoveField(model_name="teacher", name="profile_picture",),
        migrations.AddField(
            model_name="user",
            name="proflie_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="core/pictures/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
