# Generated by Django 4.1.3 on 2022-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_student_lastname_remove_student_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="proflie_picture", new_name="profile_picture",
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
