# Generated by Django 4.1.3 on 2022-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_proflie_picture_user_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="user_type",
            field=models.CharField(default="Student", max_length=255),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user_type",
            field=models.CharField(default="Teacher", max_length=255),
        ),
    ]
