# Generated by Django 4.1.3 on 2022-11-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_student_user_type_alter_teacher_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='show_revenue',
            field=models.BooleanField(default=True),
        ),
    ]
