# Generated by Django 4.1.3 on 2022-11-28 13:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_teacher_revenue_alter_teacher_show_revenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BenefitClub',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='module_id',
        ),
        migrations.RemoveField(
            model_name='module',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='questionsmultipechoice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questionstext',
            name='category',
        ),
        migrations.RemoveField(
            model_name='simulated',
            name='category',
        ),
        migrations.RemoveField(
            model_name='simulated',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='FlashCard',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='QuestionsMultipeChoice',
        ),
        migrations.DeleteModel(
            name='QuestionsText',
        ),
        migrations.DeleteModel(
            name='Simulated',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
