# Generated by Django 4.1.3 on 2022-11-28 13:31

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_benefitclub_remove_course_teacher_id_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
